export enum ErrorCode {
  // Application Errors
  EMAIL_ALREADY_IN_USE = "EMAIL_ALREADY_IN_USE",

  VALIDATION_ERROR = "VALIDATION_ERROR",

  // HTTP Errors
  BAD_REQUEST = "BAD_REQUEST",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}
